### ISSUE TITLE
[Bugs] SMF blocks when handling PDU Session SM Context update

### ISSUE THREAD

**Issue by zhonglin6666** [free5gc/free5gc#145]
## Describe the bug
AMF send SMContextUpdate request to SMF, In func HandlePDUSessionSMContextUpdate, SMF will change smContext.SMContextState to smf_context.PFCPModification. send PFCP Session Modification Request to UPF,  After reveive UPF's response,  smContext.SMContextState is Active. Chanel smContext.SBIPFCPCommunicationChan is no assignment, So SMF blocks at this:
```PFCPResponseStatus := <-smContext.SBIPFCPCommunicationChan```

## To Reproduce
Establish PDU Session Proceduce:
1. exec ./test.sh TestRegistration or ./test.sh TestN2Handover or ./test.sh TestPaging

## Expected behavior
free5GC v3.0.3 will not blocks, which has no  PFCPResponseStatus := <-smContext.SBIPFCPCommunicationChan
SMF in func HandlePDUSessionSMContextUpdate will not block, smContext.SBIPFCPCommunicationChan
 will assign After receive successful PFCP Modification Response from UPF  

## Environment (please complete the following information):
 - free5GC Version: [v3.0.4]
 - OS: [Ubuntu 18.04 Server]
 - Kernel version: [5.0.0-23-generic]
 - go version: [1.14.4 linux/amd64]
 - c compiler version (Option): [gcc version 7.4.0]

### PCAP File
[TestN2Handover.zip](https://github.com/free5gc/free5gc/files/5588841/TestN2Handover.zip)

### Log File
2020-11-24T09:35:18Z [INFO][AMF][Producer] Handle N1N2 Message Transfer Request
2020-11-24T09:35:18Z [INFO][AMF][NGAP] [AMF] Send PDU Session Resource Setup Request
2020-11-24T09:35:18Z [INFO][AMF][NGAP] [AMF] PDU Session Resource Setup Response
2020-11-24T09:35:18Z [INFO][SMF][PduSess] Recieve Update SM Context Request
2020-11-24T09:35:18Z [INFO][SMF][PduSess] In HandlePDUSessionSMContextUpdate
2020-11-24T09:35:18Z [INFO][SMF][PduSess] The SMContext State should be Active State
2020-11-24T09:35:18Z [INFO][SMF][PduSess] SMContext state:  ModificationPending
2020-11-24T09:35:18Z [INFO][SMF][Context] zzlinAAAAAAAA smContextUpdateData.HoState: ""
2020-11-24T09:35:18Z [INFO][SMF][PduSess] zzlinAAAAAAA smContext.SMContextState: 5
2020-11-24T09:35:18Z [INFO][SMF][PduSess] zzlinAAAAAAA smContext.SMContextState: 5
2020-11-24T09:35:18Z [INFO][SMF][Context] n case PFCPModification
2020-11-24T09:35:18Z [INFO][AMF][GIN] | 200 |       127.0.0.1 | POST    | /namf-comm/v1/ue-contexts/imsi-2089300007487/n1-n2-messages |
2020-11-24T09:35:18Z [INFO][UPF][Util] [PFCP] Handle PFCP session modification request
2020-11-24T09:35:18Z [INFO][SMF][Pfcp] In HandlePfcpSessionModificationResponse
2020-11-24T09:35:18Z [INFO][UPF][Util] [PFCP] Session Modification Response
2020-11-24T09:35:18Z [INFO][SMF][PduSess] [SMF] PFCP Modification Resonse Accept smContext.SMContextState: Active
2020-11-24T09:35:18Z [INFO][SMF][Pfcp] PFCP Session Modification Success[1]
2020-11-24T09:35:18Z [INFO][LIB][PFCP] Remove Request Transaction [3]

goroutine 969 [chan receive, 9 minutes]:
free5gc/src/smf/producer.HandlePDUSessionSMContextUpdate(0xc0006e43e0, 0x2d, 0xc000095520, 0x0, 0x0, 0x0, 0xc0003f1c00, 0xd, 0x3e8, 0xc00004aba8)
	**/root/go/src/free5gc/src/smf/producer/pdu_session.go:712** +0xdd6
free5gc/src/smf/pdusession.HTTPUpdateSmContext(0xc0007f5130)
	/root/go/src/free5gc/src/smf/pdusession/api_individual_sm_context.go:82 +0x410
github.com/gin-gonic/gin.(*Context).Next(0xc0007f5130)
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.4.0/context.go:124 +0x3b
github.com/gin-gonic/gin.RecoveryWithWriter.func1(0xc0007f5130)
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.4.0/recovery.go:83 +0x60
github.com/gin-gonic/gin.(*Context).Next(0xc0007f5130)
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.4.0/context.go:124 +0x3b
free5gc/lib/logger_util.ginToLogrus.func1(0xc0007f5130)
	/root/go/src/free5gc/lib/logger_util/logger_util.go:65 +0x7e
github.com/gin-gonic/gin.(*Context).Next(0xc0007f5130)
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.4.0/context.go:124 +0x3b
github.com/gin-gonic/gin.(*Engine).handleHTTPRequest(0xc00041e3c0, 0xc0007f5130)
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.4.0/gin.go:389 +0x5b0
github.com/gin-gonic/gin.(*Engine).ServeHTTP(0xc00041e3c0, 0x17b1a40, 0xc0000190a8, 0xc00093db00)
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.4.0/gin.go:351 +0x133
golang.org/x/net/http2.(*serverConn).runHandler(0xc0009c5c80, 0xc0000190a8, 0xc00093db00, 0xc0005a5920)
	/root/go/pkg/mod/golang.org/x/net@v0.0.0-20200602114024-627f9648deb9/http2/server.go:2147 +0x8b
created by golang.org/x/net/http2.(*serverConn).processHeaders
	/root/go/pkg/mod/golang.org/x/net@v0.0.0-20200602114024-627f9648deb9/http2/server.go:1881 +0x4db
exit status 2
FAIL	free5gc/src/test	601.700s
2020-11-24T07:53:40Z [INFO][UPF][Util] Removing DNN routes

Found 
```POST    | /namf-comm/v1/ue-contexts/imsi-2089300007487/n1-n2-messages    should be handled After PDUSessionSMContextUpdate procedure```

**Comment by zhonglin6666** [comment]
```
	// receive 12. NGAP-PDU Session Resource Setup Request(DL nas transport((NAS msg-PDU session setup Accept)))
	n, err = conn.Read(recvMsg)
	assert.Nil(t, err)
	_, err = ngap.Decoder(recvMsg[:n])
	assert.Nil(t, err)

	// send 14. NGAP-PDU Session Resource Setup Response
	sendMsg, err = test.GetPDUSessionResourceSetupResponse(ue.AmfUeNgapId, ue.RanUeNgapId, ranIpAddr)
	assert.Nil(t, err)
	_, err = conn.Write(sendMsg)
	assert.Nil(t, err)
```
## Problem
AMF handle N1N2 Message, During no response to SMF, AMF send PDUSessionResourceSetupRequest to RAN and UE,  UE response with PDUSessionResourceSetupResponse at once, AMF request SMF to modify SM Context, 
AMF response SMF with N1N2 message

**Comment by zhonglin6666** [comment]
Before add time.Sleep(1 * time.Second) solve this problem
``// send 14. NGAP-PDU Session Resource Setup Response
	sendMsg, err = test.GetPDUSessionResourceSetupResponse(ue.AmfUeNgapId, ue.RanUeNgapId, ranIpAddr)
	assert.Nil(t, err)
	_, err = conn.Write(sendMsg)
	assert.Nil(t, err)``` 

I think using RWLock SMContextState to solve this problem
