### ISSUE TITLE
[Bugs] SMF crash when ue preconfig has only one UPF 

### ISSUE THREAD

**Issue by zhonglin6666** [free5gc/free5gc#147]
## Describe the bug
SMF crash when ue preconfig has only one UPF, 'NewUEPreConfigPaths' childName := path.UPF[idx+1], If only on UPF, will panic: runtime error: index out of range [1] with length 1

## To Reproduce
1. uerouting config, DestinationIP: 60.60.0.200 only on UPF in path list
```
info:
  version: 1.0.0
  description: Routing information for UE

ueRoutingInfo:
  - SUPI: imsi-2089300007487
    AN: 10.200.200.101
    PathList:
      - DestinationIP: 60.60.0.101
        UPF: !!seq
          - BranchingUPF
          - AnchorUPF1

      - DestinationIP: 60.60.0.103
        UPF: !!seq
          - BranchingUPF
          - AnchorUPF2
      - DestinationIP: 60.60.0.200
        UPF: !!seq
          - AnchorUPF1

  - SUPI: imsi-2089300007486
    AN: 10.200.200.102
    PathList:
      - DestinationIP: 10.0.0.10
        UPF: !!seq
          - BranchingUPF
          - AnchorUPF1

      - DestinationIP: 10.0.0.11
        UPF: !!seq
          - BranchingUPF
          - AnchorUPF2
```
2. Run ./test_ulcl.sh TestRegistration

## Expected behavior
No panic

## Screenshots
```
Activated: false
IsDefault Path: false
Has Braching Point: false
Destination IP: 60.60.0.103
Destination Port: 
DataPath Routing Information
1th Node in the Path
Current UPF IP: 10.200.200.102
Previous UPF IP: None
Next UPF IP: 10.200.200.103
2th Node in the Path
Current UPF IP: 10.200.200.103
Previous UPF IP: 10.200.200.102
Next UPF IP: None
panic: runtime error: index out of range [1] with length 1

goroutine 40 [running]:
free5gc/src/smf/context.NewUEPreConfigPaths(0xc00040c5c0, 0x12, 0xc00009d8c0, 0x3, 0x3, 0x2, 0x2, 0xc00031b380)
	/root/go/src/free5gc/src/smf/context/ue_datapath.go:71 +0x906
free5gc/src/smf/context.InitSMFUERouting(0x2116100)
	/root/go/src/free5gc/src/smf/context/smf_context.go:199 +0x1c4
free5gc/src/smf/service.(*SMF).Start(0x266cfa0)
	/root/go/src/free5gc/src/smf/service/init.go:124 +0x57
created by free5gc/src/test_test.init.0
	/root/go/src/free5gc/src/test/ngsetup_test.go:65 +0x22a
```

## Environment (please complete the following information):
 - free5GC Version: [v3.0.4]
 - OS: [Ubuntu 18.04 Server]
 - Kernel version: [5.0.0-23-generic]
 - go version: [1.14.4 linux/amd64]
 - c compiler version (Option): [gcc version 7.4.0]

## Pull Request
[Pull Request](https://github.com/free5gc/smf/pull/10) for the fix.

**Comment by free5gc-org** [comment]
Thanks for the PR!
