### ISSUE TITLE
[Bugs] AMF crashes when  it receives InitialUEMessage before NGSetupRequest

### ISSUE THREAD

**Issue by kishiguro** [free5gc/free5gc#172]
## Describe the bug
AMF crashes when it receives InitialUEMessage before NGSetupRequest

## To Reproduce
``` text
+--------+            +-----+
| gNodeB |------------| AMF |
+--------+            +-----+
192.168.55.2          192.168.55.3
```

Let gNodeB send InitialUEMessage to 192.168.55.3 before sending NGSetupRequest.  AMF crashes with following log.

* AMF crash log
```
2021-02-11T22:15:07+09:00 [INFO][AMF][NGAP] [AMF] SCTP Accept from: 192.168.55.1/10.211.55.42/172.18.0.1/172.17.0.1:39532
2021-02-11T22:15:07+09:00 [INFO][AMF][NGAP] Create a new NG connection for: 192.168.55.1/10.211.55.42/172.18.0.1/172.17.0.1:39532
2021-02-11T22:15:07+09:00 [INFO][AMF][NGAP][192.168.55.1/10.211.55.42/172.18.0.1/172.17.0.1:39532] Handle Initial UE Message
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x9f45e0]

goroutine 19 [running]:
github.com/free5gc/fsm.(*State).Current(0x0, 0x0, 0x0)
	/home/kunihiro/go/pkg/mod/github.com/free5gc/fsm@v1.0.0/state.go:24 +0x40
github.com/free5gc/fsm.(*FSM).SendEvent(0xc00001eb20, 0x0, 0xe496de, 0xb, 0xc0004828a0, 0x0, 0xcdbe80)
	/home/kunihiro/go/pkg/mod/github.com/free5gc/fsm@v1.0.0/fsm.go:84 +0x45
github.com/free5gc/amf/nas.Dispatch(0xc000500000, 0x0, 0x0, 0xf, 0xc0004f8740, 0x20, 0xc0004f8740)
	/home/kunihiro/free5gc/NFs/amf/nas/dispatch.go:22 +0x252
github.com/free5gc/amf/nas.HandleNAS(0xc0004ba120, 0xf, 0xc000488200, 0x15, 0x20)
	/home/kunihiro/free5gc/NFs/amf/nas/handler.go:39 +0x17f
github.com/free5gc/amf/ngap.HandleInitialUEMessage(0xc0004aa000, 0xc00048a0e0)
	/home/kunihiro/free5gc/NFs/amf/ngap/handler.go:1003 +0x50d
github.com/free5gc/amf/ngap.Dispatch(0xf6d0c0, 0xc0000a0150, 0xc000484000, 0x3e, 0x2000)
	/home/kunihiro/free5gc/NFs/amf/ngap/dispatcher.go:47 +0x3dd
github.com/free5gc/amf/ngap/service.handleConnection(0xc0000a0150, 0x2000, 0xe7c780, 0xe7c788)
	/home/kunihiro/free5gc/NFs/amf/ngap/service/service.go:204 +0x729
created by github.com/free5gc/amf/ngap/service.listenAndServe
	/home/kunihiro/free5gc/NFs/amf/ngap/service/service.go:136 +0xc69
```

## Expected behavior
No crash.

## Environment (please complete the following information):
 - free5GC Version: 3.0.4
 - OS: Ubuntu 18.04
 - Kernel version: 5.0.0-23-generic
- go version: 1.14.4 linux/amd64

## Pull Request
[Pull Request](https://github.com/free5gc/amf/pull/26) for the fix.

**Comment by free5gc-org** [comment]
@kishiguro 

Should AMF send response to gNb or just ignore InitialUEMessage before receiving NGSetupRequest?

**Comment by kishiguro** [comment]
I'm not sure.  Let me check 3GPP TS 38.413.

**Comment by kishiguro** [comment]
According to spec, we may return ERROR INDICATION message with Cause IE of "Unknown local UE NGAP ID".  Although it seems it is not mandatory.  So I guess we can ignore it for now.

**Comment by free5gc-org** [comment]
Thanks for the PR! The ERROR INDICATION message will be put in the TODO list.
