### ISSUE TITLE
[Bugs] AMF breaks when a UE context is released before completing a NAS registration

### ISSUE THREAD

**Issue by p1-bmu** [free5gc/free5gc#199]
## Describe the bug
free5gc AMF panics and crashes when a UE context is released at the NGAP level by the gNodeB before the end of a NAS Registration, when NAS retransmissions with timer T3550 are ongoing. This is a standard situation that can happen in case of bad radio condition where a UE loses its radio connection while exchanging NAS signaling with the network.

Two different behavior are observed in case a UE context is released before the end of a NAS registration:
- when the UE context is released during the Authentication or Security Mode Control procedure, the AMF keeps sending NAS retransmission according to timer T3560. This is shown in the 1st pcap `free5gc_nas-reg-interrupt_crash.pcap.gz`.
- when the UE context is released after Security Mode Control but before completing the Registration, the AMF stops sending NAS retransmission according to timer T3550, but finally crashes. This is shown in the 2nd pcap `free5gc_nas-reg-interrupt_crash.pcap.gz` and the log extract below.

## To Reproduce
One way to reproduce is to modify a gNB / UE emulator, to release a UE context before the end of a NAS registration exchange. Another way is to use a real gNodeB and UE, and stops the radio radio connection or interface at the right timing before the NAS registration is completed.

## Expected behavior
free5gc AMF should not crash while processing a NGAP UE release procedure, whatever state and negotiation is ongoing at the NAS level, here with T3550 retransmission.
On another side, when a UE context is released, the AMF should stops sending NAS retransmission, as is it the case with T3560 retransmission.

## Environment (please complete the following information):
 - free5GC Version: v3.0.5
 - OS: Ubuntu 20.04
 - Kernel version: 5.4.0-62-generic
 - go version: go1.14.4 linux/amd64

### Configuration File
No specific configuration is required.

### PCAP File
When the UE context is released during T3560 retransmission, which keeps being sent:
[free5gc_nas-reg-interrupt_no-crash.pcap.gz](https://github.com/free5gc/free5gc/files/6382866/free5gc_nas-reg-interrupt_no-crash.pcap.gz)

When the UE context is released during T3550 retransmission, after which the AMF breaks:
[free5gc_nas-reg-interrupt_crash.pcap.gz](https://github.com/free5gc/free5gc/files/6382867/free5gc_nas-reg-interrupt_crash.pcap.gz)

### Log File
This is the AMF log extract when it crashes after releasing the UE context during T3550 retransmission:
```
2021-04-27T07:42:22Z [INFO][AMF][GMM][AMF_UE_NGAP_ID:14][SUPI:imsi-208690000000001] Send Registration Accept
2021-04-27T07:42:22Z [INFO][AMF][NGAP][172.27.128.253:38412][AMF_UE_NGAP_ID:14] Send Downlink Nas Transport
2021-04-27T07:42:28Z [WARN][AMF][GMM][AMF_UE_NGAP_ID:14][SUPI:imsi-208690000000001] T3550 expires, retransmit Registration Accept (retry: 1)
2021-04-27T07:42:28Z [INFO][AMF][NGAP][172.27.128.253:38412][AMF_UE_NGAP_ID:14] Send Downlink Nas Transport
2021-04-27T07:42:31Z [INFO][AMF][NGAP][172.27.128.253:38412] UE Context Release Request
2021-04-27T07:42:31Z [WARN][AMF][NGAP][172.27.128.253:38412] Cause RadioNetwork[21]
2021-04-27T07:42:31Z [INFO][AMF][NGAP][172.27.128.253:38412][AMF_UE_NGAP_ID:14] Ue Context in Non GMM-Registered
2021-04-27T07:42:31Z [INFO][AMF][NGAP][172.27.128.253:38412][AMF_UE_NGAP_ID:14] Send UE Context Release Command
2021-04-27T07:42:31Z [INFO][AMF][NGAP][172.27.128.253:38412] Handle UE Context Release Complete
2021-04-27T07:42:31Z [INFO][AMF][NGAP][172.27.128.253:38412] Release UE[imsi-208690000000001] Context : Release Ue Context
2021-04-27T07:42:34Z [WARN][AMF][GMM][AMF_UE_NGAP_ID:14][SUPI:imsi-208690000000001] [NAS] UE Context released, abort retransmission of Registration Accept
2021-04-27T07:42:40Z [WARN][AMF][GMM][AMF_UE_NGAP_ID:14][SUPI:imsi-208690000000001] [NAS] UE Context released, abort retransmission of Registration Accept
2021-04-27T07:42:46Z [WARN][AMF][GMM][AMF_UE_NGAP_ID:14][SUPI:imsi-208690000000001] [NAS] UE Context released, abort retransmission of Registration Accept
2021-04-27T07:42:52Z [WARN][AMF][GMM][AMF_UE_NGAP_ID:14][SUPI:imsi-208690000000001] T3550 Expires 4 times, abort retransmission of Registration Accept
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x100 pc=0xb9ee2d]

goroutine 247 [running]:
github.com/free5gc/amf/context.(*AmfUe).ClearRegistrationRequestData(...)
        /home/p1sec/free5gc/NFs/amf/context/amf_ue.go:537
github.com/free5gc/amf/gmm/message.SendRegistrationAccept.func2()
        /home/p1sec/free5gc/NFs/amf/gmm/message/send.go:285 +0x1ad
github.com/free5gc/amf/context.NewTimer.func1(0xc0000a9a00, 0xc00018f780, 0xc00018f740, 0xc0000c3450)
        /home/p1sec/free5gc/NFs/amf/context/timer.go:39 +0x12d
created by github.com/free5gc/amf/context.NewTimer
        /home/p1sec/free5gc/NFs/amf/context/timer.go:29 +0xd6
```

**Comment by free5gc-org** [comment]
@p1-bmu 

This issue should be fixed by https://github.com/free5gc/amf/pull/33.
Could you get the latest code (https://github.com/free5gc/amf/commit/42633d000965476d2685956d24c3e7d450e6f1a0) of AMF to test again?

**Comment by BearJim** [comment]
It would not crash with latest free5gc version. Here is no panic after T3550 retransmission when testing.
`
2021-09-07T07:52:43Z [INFO][AMF][GMM][AMF_UE_NGAP_ID:1][SUPI:imsi-2089300007487] Send Registration Accept
2021-09-07T07:52:43Z [INFO][AMF][NGAP][127.0.0.1:9487][AMF_UE_NGAP_ID:1] Send Initial Context Setup Request
2021-09-07T07:52:43Z [INFO][AMF][NGAP][127.0.0.1:9487] UE Context Release Request
2021-09-07T07:52:43Z [WARN][AMF][NGAP][127.0.0.1:9487] Cause RadioNetwork[1]
2021-09-07T07:52:43Z [INFO][AMF][NGAP][127.0.0.1:9487][AMF_UE_NGAP_ID:1] Ue Context in Non GMM-Registered
2021-09-07T07:52:43Z [INFO][AMF][NGAP][127.0.0.1:9487][AMF_UE_NGAP_ID:1] Send UE Context Release Command
2021-09-07T07:52:43Z [INFO][AMF][NGAP][127.0.0.1:9487] Handle UE Context Release Complete
2021-09-07T07:52:43Z [INFO][AMF][NGAP][127.0.0.1:9487] Release UE[imsi-2089300007487] Context : Release Ue Context
    TestRegistration: registration_test.go:198:
                Error Trace:    registration_test.go:198
                Error:          Should be true
                Test:           TestRegistration
                Messages:       No InitialContextSetup received.
2021-09-07T07:52:43Z [INFO][UDM][SDM] Handle Unsubscribe
2021-09-07T07:52:43Z [INFO][UDR][DRepo] Handle RemovesdmSubscriptions
2021-09-07T07:52:43Z [INFO][UDR][GIN] | 204 |       127.0.0.1 | DELETE  | /nudr-dr/v1/subscription-data/imsi-2089300007487/context-data/sdm-subscriptions/1 |
2021-09-07T07:52:43Z [INFO][UDM][GIN] | 204 |       127.0.0.1 | DELETE  | /nudm-sdm/v1/imsi-2089300007487/sdm-subscriptions/1 |
2021-09-07T07:52:43Z [INFO][UDM][UECM] Handle UpdateAmf3gppAccessRequest
2021-09-07T07:52:43Z [INFO][UDM][UECM] UpdateAmf3gppAccess - deregistration
2021-09-07T07:52:43Z [INFO][UDR][DRepo] Handle AmfContext3gpp
2021-09-07T07:52:43Z [INFO][UDR][GIN] | 204 |       127.0.0.1 | PATCH   | /nudr-dr/v1/subscription-data/imsi-2089300007487/context-data/amf-3gpp-access |
2021-09-07T07:52:43Z [INFO][UDM][GIN] | 204 |       127.0.0.1 | PATCH   | /nudm-uecm/v1/imsi-2089300007487/registrations/amf-3gpp-access |
2021-09-07T07:52:43Z [INFO][NAS][Message] Encode ExtendedProtocolConfigurationOptions in EncodePDUSessionEstablishmentRequest
2021-09-07T07:52:43Z [INFO][AMF][NGAP][127.0.0.1:9487] Handle Initial Context Setup Response
2021-09-07T07:52:43Z [ERRO][AMF][NGAP][127.0.0.1:9487] No UE Context[RanUeNgapID: 1]
2021-09-07T07:52:43Z [INFO][AMF][NGAP][127.0.0.1:9487] Handle Uplink Nas Transport
2021-09-07T07:52:43Z [ERRO][AMF][NGAP][127.0.0.1:9487] No UE Context[RanUeNgapID: 1]
2021-09-07T07:52:43Z [INFO][AMF][NGAP][127.0.0.1:9487] Handle Uplink Nas Transport
2021-09-07T07:52:43Z [ERRO][AMF][NGAP][127.0.0.1:9487] No UE Context[RanUeNgapID: 1]
2021-09-07T07:52:49Z [WARN][AMF][GMM][AMF_UE_NGAP_ID:1][SUPI:imsi-2089300007487] [NAS] UE Context released, abort retransmission of Registration Accept
2021-09-07T07:52:55Z [WARN][AMF][GMM][AMF_UE_NGAP_ID:1][SUPI:imsi-2089300007487] [NAS] UE Context released, abort retransmission of Registration Accept
2021-09-07T07:53:01Z [WARN][AMF][GMM][AMF_UE_NGAP_ID:1][SUPI:imsi-2089300007487] [NAS] UE Context released, abort retransmission of Registration Accept
2021-09-07T07:53:07Z [WARN][AMF][GMM][AMF_UE_NGAP_ID:1][SUPI:imsi-2089300007487] [NAS] UE Context released, abort retransmission of Registration Accept
2021-09-07T07:53:13Z [WARN][AMF][GMM][AMF_UE_NGAP_ID:1][SUPI:imsi-2089300007487] T3550 Expires 4 times, abort retransmission of Registration Accept
`
