### ISSUE TITLE
[Bugs]AMF panics on receiving Deregistration Request after receiving UEContextReleaseComplete

### ISSUE THREAD

**Issue by RyuichiNamba-fj** [free5gc/free5gc#213]
## Describe the bug
AMF panics when it receives a Deregistration Request NAS message while it has already received a UE Context Release Complete NGAP message related to the same UE.  
Some gNBs don't send UEContextReleaseComplete to UEContextReleaseCommand immediately and they might send InitialUEMessage before sending UEContextReleaseComplete.

## To Reproduce
1. RegistrationRequest ~ PDUsessionResourceSetupResponse
2. gNB -> 5GC   UEContextReleaseRequest
3. gNB <- 5GC   UEContextReleaseCommand
4. UE/gNB -> 5GC InitialUEmessage/ServiceRequest
5. UE/gNB <- 5GC  InitialContextSetupRequest/ServiceAccept
6. gNB -> 5GC InitialContextSetupResponse
7. gNB -> 5GC   UEContextReleaseComplete(Response to 3.UEContextReleaseCommand)
8. UE/gNB -> 5GC UplinkNAS/DeregistrationRequest

#### AMF panic log
```
2021-06-30T19:23:34+09:00 [INFO][AMF][GMM][AMF_UE_NGAP_ID:1][SUPI:imsi-2089300007487] Handle Deregistration Request(UE Originating) (/home/ubuntu/devel305/free5gc/NFs/amf/gmm/handler.go:2155 github.com/free5gc/amf/gmm.HandleDeregistrationRequest)
2021-06-30T19:23:34+09:00 [INFO][SMF][PduSess] Recieve Release SM Context Request (/home/ubuntu/devel305/free5gc/NFs/smf/pdusession/api_individual_sm_context.go:28 github.com/free5gc/smf/pdusession.HTTPReleaseSmContext)
2021-06-30T19:23:34+09:00 [INFO][SMF][PduSess] In HandlePDUSessionSMContextRelease (/home/ubuntu/devel305/free5gc/NFs/smf/producer/pdu_session.go:913 github.com/free5gc/smf/producer.HandlePDUSessionSMContextRelease)
2021-06-30T19:23:34+09:00 [TRAC][SMF][CTX] SMContextState Change State:  PFCPModification (/home/ubuntu/devel305/free5gc/NFs/smf/producer/pdu_session.go:1031 github.com/free5gc/smf/producer.releaseTunnel)
2021-06-30T19:23:34+09:00 [INFO][UPF][Util] [PFCP] Handle PFCP session deletion request
2021-06-30T19:23:34+09:00 [INFO][UPF][Util] [PFCP] Session Deletion Response
2021-06-30T19:23:34+09:00 [INFO][LIB][PFCP] Remove Request Transaction [6] (/home/ubuntu/go/pkg/mod/github.com/free5gc/pfcp@v1.0.0/pfcpUdp/udp.go:160 github.com/free5gc/pfcp/pfcpUdp.(*PfcpServer).RemoveTransaction)
2021-06-30T19:23:34+09:00 [INFO][SMF][PFCP] Handle PFCP Session Deletion Response (/home/ubuntu/devel305/free5gc/NFs/smf/pfcp/handler/handler.go:275 github.com/free5gc/smf/pfcp/handler.HandlePfcpSessionDeletionResponse)
2021-06-30T19:23:34+09:00 [TRAC][SMF][PduSess] Delete pending pfcp response: UPF IP [10.200.200.101] (/home/ubuntu/devel305/free5gc/NFs/smf/pfcp/handler/handler.go:296 github.com/free5gc/smf/pfcp/handler.HandlePfcpSessionDeletionResponse)
2021-06-30T19:23:34+09:00 [INFO][SMF][PFCP] PFCP Session Deletion Success[1] (/home/ubuntu/devel305/free5gc/NFs/smf/pfcp/handler/handler.go:302 github.com/free5gc/smf/pfcp/handler.HandlePfcpSessionDeletionResponse)
2021-06-30T19:23:34+09:00 [TRAC][SMF][CTX] In case SessionReleaseSuccess (/home/ubuntu/devel305/free5gc/NFs/smf/producer/pdu_session.go:963 github.com/free5gc/smf/producer.HandlePDUSessionSMContextRelease)
2021-06-30T19:23:34+09:00 [TRAC][SMF][CTX] SMContextState Change State:  InActivePending (/home/ubuntu/devel305/free5gc/NFs/smf/producer/pdu_session.go:965 github.com/free5gc/smf/producer.HandlePDUSessionSMContextRelease)
2021-06-30T19:23:34+09:00 [INFO][SMF][PduSess] UE[imsi-2089300007487] PDUSessionID[10] Release IP[60.60.0.1] (/home/ubuntu/devel305/free5gc/NFs/smf/context/sm_context.go:189 github.com/free5gc/smf/context.RemoveSMContext)
2021-06-30T19:23:34+09:00 [DEBU][SMF][CTX] [{60.60.0.2 - 60.60.255.254}->{60.60.0.1 - 60.60.0.1}] (/home/ubuntu/devel305/free5gc/NFs/smf/context/user_plane_information.go:647 github.com/free5gc/smf/context.(*UeIPPool).release)
2021-06-30T19:23:34+09:00 [INFO][SMF][GIN] | 204 |       127.0.0.1 | POST    | /nsmf-pdusession/v1/sm-contexts/urn:uuid:bb95b73b-0b49-4512-bc32-6944428eb262/release | (/home/ubuntu/devel305/free5gc/lib/logger_util/logger_util.go:157 github.com/free5gc/logger_util.ginToLogrus.func1)
2021-06-30T19:23:34+09:00 [INFO][PCF][Ampolicy] Handle AM Policy Association Delete
2021-06-30T19:23:34+09:00 [INFO][PCF][GIN] | 204 |       127.0.0.1 | DELETE  | /npcf-am-policy-control/v1/policies/imsi-2089300007487-1 |
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x90 pc=0x10250c6]

goroutine 309 [running]:
github.com/free5gc/amf/gmm/message.SendDeregistrationAccept(0x0)
        /home/ubuntu/devel305/free5gc/NFs/amf/gmm/message/send.go:240 +0x26
github.com/free5gc/amf/gmm.HandleDeregistrationRequest(0xc0000dd600, 0x173171b, 0xb, 0xc00051d290, 0x1, 0xc00047b0e0)
        /home/ubuntu/devel305/free5gc/NFs/amf/gmm/handler.go:2194 +0xb86
github.com/free5gc/amf/gmm.DeregisteredInitiated(0xc000623d10, 0x1731999, 0xb, 0xc00051da70)
        /home/ubuntu/devel305/free5gc/NFs/amf/gmm/sm.go:364 +0x68d
github.com/free5gc/fsm.(*FSM).SendEvent(0xc000438280, 0xc000623d10, 0x174f4cf, 0x19, 0xc00051da70, 0x11, 0x19)
        /home/ubuntu/go/pkg/mod/github.com/free5gc/fsm@v1.0.0/fsm.go:100 +0x2f4
github.com/free5gc/amf/gmm.Registered(0xc000623d10, 0x1731a5f, 0xb, 0xc00051d7a0)
        /home/ubuntu/devel305/free5gc/NFs/amf/gmm/sm.go:99 +0x6e6
github.com/free5gc/fsm.(*FSM).SendEvent(0xc000438280, 0xc000623d10, 0x1731a5f, 0xb, 0xc00051d7a0, 0x1bac9f0, 0x14894e0)
        /home/ubuntu/go/pkg/mod/github.com/free5gc/fsm@v1.0.0/fsm.go:95 +0x22d
github.com/free5gc/amf/nas.Dispatch(0xc0000dd600, 0x173171b, 0xb, 0x2e, 0xc00098b1c0, 0x19, 0xc00098b1c0)
        /home/ubuntu/devel305/free5gc/NFs/amf/nas/dispatch.go:27 +0x29e
github.com/free5gc/amf/nas.HandleNAS(0xc0005c9680, 0x2e, 0xc0001a5c20, 0x18, 0x20)
        /home/ubuntu/devel305/free5gc/NFs/amf/nas/handler.go:39 +0x178
github.com/free5gc/amf/ngap.HandleUplinkNasTransport(0xc00056be00, 0xc00098a0a0)
        /home/ubuntu/devel305/free5gc/NFs/amf/ngap/handler.go:234 +0x701
github.com/free5gc/amf/ngap.Dispatch(0x1c01ea0, 0xc000523490, 0xc0008f0000, 0x43, 0x2000)
        /home/ubuntu/devel305/free5gc/NFs/amf/ngap/dispatcher.go:49 +0x527
github.com/free5gc/amf/ngap/service.handleConnection(0xc000523490, 0x2000, 0x179b538, 0x179b540)
        /home/ubuntu/devel305/free5gc/NFs/amf/ngap/service/service.go:204 +0x700
created by github.com/free5gc/amf/ngap/service.listenAndServe
        /home/ubuntu/devel305/free5gc/NFs/amf/ngap/service/service.go:136 +0xc43
```

## Expected behavior
No panic.

## Root cause
AMF panics caused by nil pointer dereference in SendDeregistrationAccept() since ue.AmfUe is made nil at receiving UecontextReleaseComplete.
```go
func SendDeregistrationAccept(ue *context.RanUe) {
	ue.AmfUe.GmmLog.Info("Send Deregistration Accept") ★

}
```
So, We have fixed AMF not to send DeregistrationAccept if UE State is CM-IDLE.  
AMF should not call SendDeregistrationAccept() when the UE is in CM-IDLE.

The issue  [#199](https://github.com/free5gc/free5gc/issues/199) is similar problem.

## Environment (please complete the following information):
 - free5GC Version: 3.0.5
 - OS: Ubuntu 18.04
 - Kernel version: 5.0.0-23-generic
 - go version: go version go1.14.4 linux/amd64

## Pull Request
[Pull Request](https://github.com/free5gc/amf/pull/33) for the fix.
This fixes the issue [#199](https://github.com/free5gc/free5gc/issues/199), too.

**Comment by free5gc-org** [comment]
Thanks for the PR!
