### ISSUE TITLE
[Bugs] AMF panics when smContext doesn't exist

### ISSUE THREAD

**Issue by mariakagi** [free5gc/free5gc#354]
## Describe the bug
AMF panics when smContext doesn't exist".

## To Reproduce
1. Establish PDU Session with **PSI=10**
2. UE Context Release
3. Send Service Request
4. Receive Service Accept/Initial Context Setup Request
5. Send Initial Context Setup Response 
	PDU Session Resource Setup Response List in the message includes **PSI=11**

## Expected behavior
AMF doesn't panic and ignores unknown PSI.

## Environment
 - free5GC Version: v3.1.1
 - OS: Ubuntu 18.04
 - Kernel version: 5.0.0-23-generic
 - go version go1.14.4 linux/amd64

### Log File
```
2022-06-23T00:10:56Z [INFO][AMF][NGAP][127.0.1.1:9784][AMF_UE_NGAP_ID:2] Handle Initial Context Setup Response (/home/fujitsu/github/free5gc/NFs/amf/internal/ngap/handler.go:1660 github.com/free5gc/amf/internal/ngap.HandleInitialContextSetupResponse)
2022-06-23T00:10:56Z [ERRO][AMF][NGAP][127.0.1.1:9784][AMF_UE_NGAP_ID:2] SmContext[PDU Session ID:11] not found (/home/fujitsu/github/free5gc/NFs/amf/internal/ngap/handler.go:1670 github.com/free5gc/amf/internal/ngap.HandleInitialContextSetupResponse)
2022/06/23 00:10:56 SCTP Connection for 127.0.0.1:38412 is closed
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xa6fe3b]

goroutine 4 [running]:
github.com/free5gc/amf/internal/context.(*SmContext).SmfUri(0x0, 0x0, 0x0)
        /home/fujitsu/github/free5gc/NFs/amf/internal/context/sm_context.go:148 +0x3b
github.com/free5gc/amf/internal/sbi/consumer.SendUpdateSmContextRequest(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/fujitsu/github/free5gc/NFs/amf/internal/sbi/consumer/sm_context.go:405 +0x108
github.com/free5gc/amf/internal/sbi/consumer.SendUpdateSmContextN2Info(0xc0001ec000, 0x0, 0xe7de4d, 0x11, 0xc00020d800, 0xd, 0x10, 0xc0001ec000, 0x52, 0x60, ...)
        /home/fujitsu/github/free5gc/NFs/amf/internal/sbi/consumer/sm_context.go:259 +0x140
github.com/free5gc/amf/internal/ngap.HandleInitialContextSetupResponse(0xc0002d6080, 0xc0003093c0)
        /home/fujitsu/github/free5gc/NFs/amf/internal/ngap/handler.go:1673 +0x919
```
## Additional context
[Pull Request](https://github.com/free5gc/amf/pull/72) for the fix.

**Comment by ianchen0119** [comment]
@mariakagi 

Thanks for your contribution!
we will review your changes as soon as possilbe.
