### ISSUE TITLE
[Bugs]AMF panics when it receives SecurityModeComplete with ServiceRequest set to the NAS message container.

### ISSUE THREAD

**Issue by RyuichiNamba-fj** [free5gc/free5gc#375]
## Describe the bug
AMF panics when it receives SecurityModeComplete with ServiceRequest set to the NAS message container.

## To Reproduce
SecurityModeComplete is sent with SeriveRequest during the registration procedure.

## Expected behavior
- If ServiceRequest is received while -Registaration is not completed, return ServiceReject.
- If the ServiceRequest is received while -Registaration is completed, it is accepted.

## Environment (please complete the following information):
- free5GC Version: v3.2.1
- OS: Ubuntu 18.04
- Kernel version: 5.0.0-23-generic
- go version go1.14.4 linux/amd64

### Log File
console log
```
2022-07-28T05:52:42Z [INFO][AMF][NGAP][127.0.1.1:9784][AMF_UE_NGAP_ID:1] Uplink NAS Transport (RAN UE NGAP ID: 1) (/home/fujitsu/Origin-go-upf/free5gc/NFs/amf/internal/ngap/handler.go:227 github.com/free5gc/amf/internal/ngap.HandleUplinkNasTransport)
2022-07-28T05:52:42Z [INFO][LIB][FSM] Handle event[Gmm Message], transition from [SecurityMode] to [SecurityMode] (/home/fujitsu/go/pkg/mod/github.com/free5gc/util@v1.0.3/fsm/fsm.go:95 github.com/free5gc/util/fsm.(*FSM).SendEvent)
2022-07-28T05:52:42Z [INFO][AMF][GMM][AMF_UE_NGAP_ID:1][SUPI:imsi-2089300007487] Handle Security Mode Complete (/home/fujitsu/Origin-go-upf/free5gc/NFs/amf/internal/gmm/handler.go:2173 github.com/free5gc/amf/internal/gmm.HandleSecurityModeComplete)
2022-07-28T05:52:42Z [INFO][LIB][FSM] Handle event[SecurityMode Success], transition from [SecurityMode] to [ContextSetup] (/home/fujitsu/go/pkg/mod/github.com/free5gc/util@v1.0.3/fsm/fsm.go:95 github.com/free5gc/util/fsm.(*FSM).SendEvent)
2022-07-28T05:52:42Z [INFO][AMF][GMM][AMF_UE_NGAP_ID:1][SUPI:imsi-2089300007487] Handle InitialRegistration (/home/fujitsu/Origin-go-upf/free5gc/NFs/amf/internal/gmm/handler.go:573 github.com/free5gc/amf/internal/gmm.HandleInitialRegistration)
2022-07-28T05:52:42Z [INFO][NRF][DSCV] Handle NFDiscoveryRequest (/home/fujitsu/Origin-go-upf/free5gc/NFs/nrf/internal/sbi/producer/nf_discovery.go:23 github.com/free5gc/nrf/internal/sbi/producer.HandleNFDiscoveryRequest)
2022-07-28T05:52:42Z [INFO][NRF][GIN] | 200 |       127.0.0.1 | GET     | /nnrf-disc/v1/nf-instances?requester-nf-type=AMF&supi=imsi-2089300007487&target-nf-type=UDM | (/home/fujitsu/go/pkg/mod/github.com/free5gc/util@v1.0.3/logger/logger.go:190 github.com/free5gc/util/logger.ginToLogrus.func1)
2022-07-28T05:52:42Z [INFO][UDM][SDM] Handle GetNssai (/home/fujitsu/Origin-go-upf/free5gc/NFs/udm/internal/sbi/producer/subscriber_data_management.go:686 github.com/free5gc/udm/internal/sbi/producer.HandleGetNssaiRequest)
2022-07-28T05:52:42Z [INFO][UDR][DRepo] Handle QueryAmData (/home/fujitsu/Origin-go-upf/free5gc/NFs/udr/internal/sbi/producer/data_repository.go:62 github.com/free5gc/udr/internal/sbi/producer.HandleQueryAmData)
2022-07-28T05:52:42Z [INFO][UDR][GIN] | 200 |       127.0.0.1 | GET     | /nudr-dr/v1/subscription-data/imsi-2089300007487/20893/provisioned-data/am-data?supported-features= | (/home/fujitsu/go/pkg/mod/github.com/free5gc/util@v1.0.3/logger/logger.go:190 github.com/free5gc/util/logger.ginToLogrus.func1)
2022-07-28T05:52:42Z [INFO][UDM][GIN] | 200 |       127.0.0.1 | GET     | /nudm-sdm/v1/imsi-2089300007487/nssai?plmn-id=%7B%22mcc%22%3A%22208%22%2C%22mnc%22%3A%2293%22%7D | (/home/fujitsu/go/pkg/mod/github.com/free5gc/util@v1.0.3/logger/logger.go:190 github.com/free5gc/util/logger.ginToLogrus.func1)
2022/07/28 05:52:42 SCTP Connection for 127.0.0.1:38412 is closed
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0xbe599e]

goroutine 49 [running]:
github.com/free5gc/amf/internal/gmm.handleRequestedNssai(0xc0004bc000, 0xe793be, 0xb, 0x1, 0x1)
        /home/fujitsu/Origin-go-upf/free5gc/NFs/amf/internal/gmm/handler.go:1194 +0x3e
github.com/free5gc/amf/internal/gmm.HandleInitialRegistration(0xc0004bc000, 0xe793be, 0xb, 0x1, 0x1)
        /home/fujitsu/Origin-go-upf/free5gc/NFs/amf/internal/gmm/handler.go:585 +0xfe
github.com/free5gc/amf/internal/gmm.ContextSetup(0xc00052edb0, 0xe794e7, 0xb, 0xc0005e7140)
        /home/fujitsu/Origin-go-upf/free5gc/NFs/amf/internal/gmm/sm.go:302 +0x1049
github.com/free5gc/util/fsm.(*FSM).SendEvent(0xc000068860, 0xc00052edb0, 0xe8053b, 0x14, 0xc0005e7140, 0x0, 0x0)
        /home/fujitsu/go/pkg/mod/github.com/free5gc/util@v1.0.3/fsm/fsm.go:108 +0x429
github.com/free5gc/amf/internal/gmm.HandleSecurityModeComplete(0xc0004bc000, 0xe793be, 0xb, 0x2e, 0xc0005f7740, 0xf0, 0x20b)
        /home/fujitsu/Origin-go-upf/free5gc/NFs/amf/internal/gmm/handler.go:2207 +0x423
github.com/free5gc/amf/internal/gmm.SecurityMode(0xc00052edb0, 0xe7956b, 0xb, 0xc0005e6f60)
        /home/fujitsu/Origin-go-upf/free5gc/NFs/amf/internal/gmm/sm.go:255 +0x809
github.com/free5gc/util/fsm.(*FSM).SendEvent(0xc000068860, 0xc00052edb0, 0xe7956b, 0xb, 0xc0005e6f60, 0xfd3000, 0xcdf160)
        /home/fujitsu/go/pkg/mod/github.com/free5gc/util@v1.0.3/fsm/fsm.go:98 +0x2c6
github.com/free5gc/amf/internal/nas.Dispatch(0xc0004bc000, 0xe793be, 0xb, 0x2e, 0xc0005f76a0, 0x29, 0xc0005f76a0)
        /home/fujitsu/Origin-go-upf/free5gc/NFs/amf/internal/nas/dispatch.go:27 +0x29e
github.com/free5gc/amf/internal/nas.HandleNAS(0xc0006ac6c0, 0x2e, 0xc00025c090, 0x2a, 0x30)
        /home/fujitsu/Origin-go-upf/free5gc/NFs/amf/internal/nas/handler.go:33 +0x169
github.com/free5gc/amf/internal/ngap.HandleUplinkNasTransport(0xc000690080, 0xc0005f65e0)
        /home/fujitsu/Origin-go-upf/free5gc/NFs/amf/internal/ngap/handler.go:233 +0x698
github.com/free5gc/amf/internal/ngap.Dispatch(0x1000620, 0xc000068350, 0xc0005fa000, 0x55, 0x2000)
        /home/fujitsu/Origin-go-upf/free5gc/NFs/amf/internal/ngap/dispatcher.go:49 +0x527
github.com/free5gc/amf/internal/ngap/service.handleConnection(0xc000068350, 0x2000, 0xeaf6d8, 0xeaf6e0)
        /home/fujitsu/Origin-go-upf/free5gc/NFs/amf/internal/ngap/service/service.go:204 +0x700
```

## Additional context
I have sennt a [PR](https://github.com/free5gc/amf/pull/76).

**Comment by ianchen0119** [comment]
Hi @RyuichiNamba-fj 

I'm just curios to know: How did you produce this problem?
As I know,
Service request should be triggered while UE is in registered state (UE received the paging message for downlink data).

Thanks.

**Comment by RyuichiNamba-fj** [comment]
@ianchen0119 
Yes, you are correct, ServiceRequest is triggered when the UE is in Registered and CM-IDLE state.
This problem occurred only once when real UE and real gNB were used. I am assuming that it is probably a bug in one of them.
This PR is a workaround in case such a problem should occur.

**Comment by ianchen0119** [comment]
@RyuichiNamba-fj 

Ok, I got it!
Thanks for your explanation.

**Comment by tim-ywliu** [comment]
Thanks for the PR.
