### ISSUE TITLE
[Bugs] NRF panics for unknown targetNfType in /oauth2/token

### ISSUE THREAD

**Issue by GKnirps** [free5gc/free5gc#434]
## Describe the bug
When I call the `/oauth2/token` endpoint of the NRF with an invalid/unknown `targetNfType`, it returns a 500 Internal Server Error and logs a nil pointer dereference panic

## To Reproduce
1. Start the NRF
2. register with the NRF as a network function via `PUT /nnrf-nfm/v1/nf-instances/<ID>`
3. send a POST request to the NRF endpoint `/oauth2/token` with the following payload:
    ```
    {
        "nfInstanceId": "<the UUID you registered in step 2>",
        "grant_type": "client_credentials",
        "nfType": "<whatever you used in step 2>",
        "targetNfType: "NOPE",
        "scope": "nudr-dr"
    }
    ```
=> a 500 Internal Server Error will be returned

## Expected behavior
I expect a 400 Bad Request, where the body contains JSON in the form of `{"error": "<error-string>"}`

The exact value `<error-string>` is left a bit unclear in the specification as far as I can tell, but it should be one of `invalid_scope`, `invalid_client`, `unauthorized_client` or `invalid_request`. Consistent with other behaviour of the Free5gc implementation would be `invalid_client`.

## Environment (please complete the following information):
 - free5GC Version: NRF git-commit `0cc35b002c2cf1e80b05a19923d2d684daa78456`, free5gc git-commit `e6f787dcd3bee221f44a5c807b605d380256a404`
 - OS: Debian GNU/Linux Bullseye
 - Kernel version: 6.1.12
 - go version: 1.18.10 linux/amd64

### Configuration File

```
info:
  version: 1.0.2
  description: NRF initial local configuration

configuration:
  MongoDBName: free5gc # database name in MongoDB
  MongoDBUrl: mongodb://172.44.0.2:27017 # a valid URL of the mongodb
  sbi: # Service-based interface information
    scheme: https # the protocol for sbi (http or https)
    registerIPv4: 172.44.0.12 # IP used to serve NFs or register to another NRF
    bindingIPv4: 172.44.0.12 # IP used to bind the service
    port: 8000 # port used to bind the service
    cert: # the local path of TLS key
      pem: ./config/TLS/nrf.pem # NRF TLS Certificate
      key: ./config/TLS/nrf.key # NRF TLS Private key
    rootcert:
      pem: ./config/TLS/nrf.pem # NRF TLS Certificate
      key: ./config/TLS/nrf.key # NRF TLS Private key
    oauth: true
  DefaultPlmnId:
    mcc: 001 # Mobile Country Code (3 digits string, digit: 0~9)
    mnc: 01 # Mobile Network Code (2 or 3 digits string, digit: 0~9)
  serviceNameList: # the SBI services provided by this NRF, refer to TS 29.510
    - nnrf-nfm # Nnrf_NFManagement service
    - nnrf-disc # Nnrf_NFDiscovery service

# the kind of log output
# debugLevel: how detailed to output, value: trace, debug, info, warn, error, fatal, panic
# ReportCaller: enable the caller report or not, value: true or false
logger:
  NRF:
    debugLevel: info
    ReportCaller: false
```

### Log File
Github does not allow me to attach the logfile to I have to paste the relevant part here:
```
nrf      | 2023-03-10T09:06:36.510663071Z [INFO][NRF][Token] In HTTPAccessTokenRequest
nrf      | 2023-03-10T09:06:36.511746724Z [INFO][NRF][Token] Handle AccessTokenRequest
nrf      | 2023-03-10T09:06:36.511869714Z [INFO][NRF][Token] In AccessTokenProcedure
nrf      | 2023-03-10T09:06:36.514064258Z [ERRO][NRF][GIN] panic: runtime error: invalid memory address or nil pointer dereference
nrf      | goroutine 31733 [running]:
nrf      | runtime/debug.Stack()
nrf      | 	/usr/local/go/src/runtime/debug/stack.go:24 +0x65
nrf      | github.com/free5gc/util/logger.ginRecover.func1.1()
nrf      | 	/go/pkg/mod/github.com/free5gc/util@v1.0.3/logger/logger.go:212 +0x1a5
nrf      | panic({0xc25a00, 0x1382e70})
nrf      | 	/usr/local/go/src/runtime/panic.go:838 +0x207
nrf      | github.com/free5gc/nrf/internal/sbi/producer.AccessTokenScopeCheck({{0xc00084a03d, 0x12}, {0xc00084a00d, 0x24}, {0xc00084a057, 0x3}, {0xc00084a068, 0x4}, {0xc00084a073, 0x7}, ...})
nrf      | 	/go/src/free5gc/NFs/nrf/internal/sbi/producer/access_token.go:181 +0x754
nrf      | github.com/free5gc/nrf/internal/sbi/producer.AccessTokenProcedure({{0xc00084a03d, 0x12}, {0xc00084a00d, 0x24}, {0xc00084a057, 0x3}, {0xc00084a068, 0x4}, {0xc00084a073, 0x7}, ...})
nrf      | 	/go/src/free5gc/NFs/nrf/internal/sbi/producer/access_token.go:53 +0xf8
nrf      | github.com/free5gc/nrf/internal/sbi/producer.HandleAccessTokenRequest(0xc000630030)
nrf      | 	/go/src/free5gc/NFs/nrf/internal/sbi/producer/access_token.go:28 +0x11c
nrf      | github.com/free5gc/nrf/internal/sbi/accesstoken.HTTPAccessTokenRequest(0xc00056a400)
nrf      | 	/go/src/free5gc/NFs/nrf/internal/sbi/accesstoken/api_access_token_request.go:86 +0x932
nrf      | github.com/gin-gonic/gin.(*Context).Next(...)
nrf      | 	/go/pkg/mod/github.com/gin-gonic/gin@v1.7.3/context.go:165
nrf      | github.com/free5gc/util/logger.ginRecover.func1(0xc00056a400)
nrf      | 	/go/pkg/mod/github.com/free5gc/util@v1.0.3/logger/logger.go:244 +0x7b
nrf      | github.com/gin-gonic/gin.(*Context).Next(...)
nrf      | 	/go/pkg/mod/github.com/gin-gonic/gin@v1.7.3/context.go:165
nrf      | github.com/free5gc/util/logger.ginToLogrus.func1(0xc00056a400)
nrf      | 	/go/pkg/mod/github.com/free5gc/util@v1.0.3/logger/logger.go:179 +0x87
nrf      | github.com/gin-gonic/gin.(*Context).Next(...)
nrf      | 	/go/pkg/mod/github.com/gin-gonic/gin@v1.7.3/context.go:165
nrf      | github.com/gin-gonic/gin.(*Engine).handleHTTPRequest(0xc00052f040, 0xc00056a400)
nrf      | 	/go/pkg/mod/github.com/gin-gonic/gin@v1.7.3/gin.go:489 +0x63e
nrf      | github.com/gin-gonic/gin.(*Engine).ServeHTTP(0xc00052f040, {0xeda368?, 0xc000612270}, 0xc0005b7400)
nrf      | 	/go/pkg/mod/github.com/gin-gonic/gin@v1.7.3/gin.go:445 +0x1c5
nrf      | golang.org/x/net/http2.(*serverConn).runHandler(0xed9aa0?, 0x13d6d68?, 0x0?, 0x0?)
nrf      | 	/go/pkg/mod/golang.org/x/net@v0.0.0-20210805182204-aaa1db679c0d/http2/server.go:2158 +0x78
nrf      | created by golang.org/x/net/http2.(*serverConn).processHeaders
nrf      | 	/go/pkg/mod/golang.org/x/net@v0.0.0-20210805182204-aaa1db679c0d/http2/server.go:1888 +0x52b
```

## System architecture (Option)
A Docker setup  using docker-compose

## Walkthrough (Option)
I was doing some security checks on the NRF. Other than this bug, I found that despite pretending to do some client certificate checks (it loads the certificate for whatever NF the client claims to be from the local disk and verifies that against a root CA), the client's actual certificate in the request is never verified. Any client can get an access token without any restrictions.

## Additional context
I have prepared [a fix](https://github.com/free5gc/nrf/commit/de080a5cb5a26e2fb1789aaa3436d634b0e9a331) and I can make a pull request if you want me to.

**Comment by GKnirps** [comment]
That should be fixed with [this pull request](https://github.com/free5gc/nrf/pull/16).

**Comment by GKnirps** [comment]
Fix works.
