### ISSUE TITLE
[Bugs] Not comprehended IE in NGAP message

### ISSUE THREAD

**Issue by ShouheiNishi** [free5gc/free5gc#443]
## Describe the bug
When AMF receives NGAP message includes not comprehended but ignore IE,
AMF should skip this IE and continue to process other IEs.
But these NGAP message is rejected by APER decoder in current version of free5GC.

## To Reproduce
1. Apply this patch
```
diff --git a/test/registration_test.go b/test/registration_test.go
index 19a75ef..e30d029 100644
--- a/test/registration_test.go
+++ b/test/registration_test.go
@@ -56,6 +56,8 @@ func TestRegistration(t *testing.T) {
        // send NGSetupRequest Msg
        sendMsg, err = test.GetNGSetupRequest([]byte("\x00\x01\x02"), 24, "free5gc")
        assert.Nil(t, err)
+       sendMsg[0x13] = 0x55
+       sendMsg[0x14] = 0x55
        _, err = conn.Write(sendMsg)
        assert.Nil(t, err)

```
2. Run `./test.sh -o TestRegistration`

## Expected behavior
Process these packet

## Screenshots
```
$ make upf && ./test.sh -o TestRegistration
Start building upf....
cd NFs/upf/cmd && \
CGO_ENABLED=0 go build -gcflags "" -ldflags "-X github.com/free5gc/util/version.VERSION=v3.2.1-14-g662c019 -X github.com/free5gc/util/version.BUILD_TIME=2023-04-28T04:11:51Z -X github.com/free5gc/util/version.COMMIT_HASH=e05c3433 -X github.com/free5gc/util/version.COMMIT_TIME=2022-09-02T01:58:48Z" -o /home/nishi/free5gc-deb/free5gc/bin/upf main.go
2023-04-28T13:12:11+09:00 [INFO][UPF][Main] UPF version:
        free5GC version: v3.2.1-14-g662c019
        build time:      2023-04-28T04:11:51Z
        commit hash:     e05c3433
        commit time:     2022-09-02T01:58:48Z
        go version:      go1.20.3 linux/amd64
2023-04-28T13:12:11+09:00 [INFO][UPF][Cfg] Read config from [./config/upfcfg.test.yaml]
2023-04-28T13:12:11+09:00 [INFO][UPF][Cfg] ==================================================
2023-04-28T13:12:11+09:00 [INFO][UPF][Cfg] (*factory.Config)(0xc000402690)({
        Version: (string) (len=5) "1.0.3",
        Description: (string) (len=31) "UPF initial local configuration",
        Pfcp: (*factory.Pfcp)(0xc00040ef60)({
                Addr: (string) (len=14) "10.200.200.101",
                NodeID: (string) (len=14) "10.200.200.101",
                RetransTimeout: (time.Duration) 1s,
                MaxRetrans: (uint8) 3
        }),
        Gtpu: (*factory.Gtpu)(0xc00040f110)({
                Forwarder: (string) (len=5) "gtp5g",
                IfList: ([]factory.IfInfo) (len=1 cap=1) {
                        (factory.IfInfo) {
                                Addr: (string) (len=14) "10.200.200.102",
                                Type: (string) (len=2) "N3",
                                Name: (string) "",
                                IfName: (string) "",
                                MTU: (uint32) 0
                        }
                }
        }),
        DnnList: ([]factory.DnnList) (len=1 cap=1) {
                (factory.DnnList) {
                        Dnn: (string) (len=8) "internet",
                        Cidr: (string) (len=12) "10.60.0.0/16",
                        NatIfName: (string) ""
                }
        },
        Logger: (*factory.Logger)(0xc0003e4d80)({
                Enable: (bool) true,
                Level: (string) (len=4) "info",
                ReportCaller: (bool) false
        })
})
2023-04-28T13:12:11+09:00 [INFO][UPF][Cfg] ==================================================
2023-04-28T13:12:11+09:00 [INFO][UPF][Main] Log level is set to [info] level
2023-04-28T13:12:11+09:00 [INFO][UPF][Main] starting Gtpu Forwarder [gtp5g]
2023-04-28T13:12:11+09:00 [INFO][UPF][Main] GTP Address: "10.200.200.102:2152"
2023-04-28T13:12:11+09:00 [ERRO][UPF][Main] UPF Cli Run Error: open Gtp5g: version mismatch: operation not supported
tcpdump: listening on any, link-type LINUX_SLL (Linux cooked v1), capture size 262144 bytes
tcpdump: listening on lo, link-type EN10MB (Ethernet), capture size 262144 bytes
Run TestRegistration
2023-04-28T13:12:34+09:00 [INFO][NRF][CFG] config version [1.0.1]
2023-04-28T13:12:34+09:00 [INFO][AMF][CFG] config version [1.0.3]
2023-04-28T13:12:34+09:00 [INFO][SMF][CFG] SMF config version [1.0.2]
2023-04-28T13:12:34+09:00 [INFO][SMF][CFG] UE-Routing config version [1.0.1]
2023-04-28T13:12:34+09:00 [INFO][UDR][CFG] config version [1.0.1]
2023-04-28T13:12:34+09:00 [INFO][PCF][CFG] config version [1.0.1]
2023-04-28T13:12:34+09:00 [INFO][UDM][CFG] config version [1.0.2]
2023-04-28T13:12:34+09:00 [INFO][NSSF][CFG] config version [1.0.1]
2023-04-28T13:12:34+09:00 [INFO][AUSF][CFG] config version [1.0.2]
2023-04-28T13:12:34+09:00 [INFO][NRF][Init] NRF Log level is set to [info] level
2023-04-28T13:12:34+09:00 [INFO][NRF][Init] Server started
2023-04-28T13:12:34+09:00 [INFO][NRF][Init] nrfconfig Info: Version[1.0.1] Description[NRF initial test configuration]
2023-04-28T13:12:34+09:00 [INFO][NRF][Init] Binding addr: [127.0.0.10:8000]
2023-04-28T13:12:34+09:00 [INFO][AMF][Init] AMF Log level is set to [info] level
2023-04-28T13:12:34+09:00 [INFO][LIB][NAS] set log level : info
2023-04-28T13:12:34+09:00 [INFO][LIB][NAS] set report call : false
2023-04-28T13:12:34+09:00 [INFO][LIB][NGAP] set log level : info
2023-04-28T13:12:34+09:00 [INFO][LIB][NGAP] set report call : false
2023-04-28T13:12:34+09:00 [INFO][LIB][FSM] set log level : info
2023-04-28T13:12:34+09:00 [INFO][LIB][FSM] set report call : false
2023-04-28T13:12:34+09:00 [INFO][LIB][Aper] set log level : info
2023-04-28T13:12:34+09:00 [INFO][LIB][Aper] set report call : false
2023-04-28T13:12:34+09:00 [INFO][AMF][Init] Server started
2023-04-28T13:12:34+09:00 [INFO][AMF][Util] amfconfig Info: Version[1.0.3] Description[AMF initial test configuration]
2023-04-28T13:12:34+09:00 [INFO][AMF][NGAP] Listen on 127.0.0.1:38412
2023-04-28T13:12:34+09:00 [INFO][NRF][MGMT] Handle NFRegisterRequest
2023-04-28T13:12:34+09:00 [INFO][NRF][MGMT] urilist create
2023-04-28T13:12:34+09:00 [INFO][NRF][MGMT] Create NF Profile
2023-04-28T13:12:34+09:00 [INFO][NRF][MGMT] Location header:  http://127.0.0.10:8000/nnrf-nfm/v1/nf-instances/2c2f3fcb-b528-4eb0-b929-115b06238a57
2023-04-28T13:12:34+09:00 [INFO][NRF][GIN] | 201 |       127.0.0.1 | PUT     | /nnrf-nfm/v1/nf-instances/2c2f3fcb-b528-4eb0-b929-115b06238a57 |
2023-04-28T13:12:34+09:00 [INFO][SMF][Init] SMF Log level is set to [info] level
2023-04-28T13:12:34+09:00 [INFO][LIB][NAS] set log level : info
2023-04-28T13:12:34+09:00 [INFO][LIB][NAS] set report call : false
2023-04-28T13:12:34+09:00 [INFO][LIB][NGAP] set log level : info
2023-04-28T13:12:34+09:00 [INFO][LIB][NGAP] set report call : false
2023-04-28T13:12:34+09:00 [INFO][LIB][Aper] set log level : info
2023-04-28T13:12:34+09:00 [INFO][LIB][Aper] set report call : false
2023-04-28T13:12:34+09:00 [INFO][LIB][PFCP] set log level : info
2023-04-28T13:12:34+09:00 [INFO][LIB][PFCP] set report call : false
2023-04-28T13:12:34+09:00 [INFO][SMF][CTX] smfconfig Info: Version[1.0.2] Description[SMF initial single test configuration]
2023-04-28T13:12:34+09:00 [INFO][SMF][CTX] Endpoints: [10.200.200.102]
2023-04-28T13:12:34+09:00 [INFO][SMF][Init] Server started
2023-04-28T13:12:34+09:00 [INFO][NRF][MGMT] Handle NFRegisterRequest
2023-04-28T13:12:34+09:00 [INFO][NRF][MGMT] urilist create
2023-04-28T13:12:34+09:00 [INFO][NRF][MGMT] Create NF Profile
2023-04-28T13:12:34+09:00 [INFO][NRF][MGMT] Location header:  http://127.0.0.10:8000/nnrf-nfm/v1/nf-instances/a092e597-a744-44a7-8ace-5533797574a5
2023-04-28T13:12:34+09:00 [INFO][NRF][GIN] | 201 |       127.0.0.1 | PUT     | /nnrf-nfm/v1/nf-instances/a092e597-a744-44a7-8ace-5533797574a5 |
2023-04-28T13:12:34+09:00 [INFO][SMF][Init] SMF Registration to NRF {a092e597-a744-44a7-8ace-5533797574a5 SMF REGISTERED 0 0xc00012fb78 0xc00012fba8 [] []   [127.0.0.2] [] <nil> [] [] <nil> 0 0 0  <nil> <nil> <nil> <nil> 0xc0006d7600 <nil> <nil> <nil> <nil> <nil> map[] <nil> false 0xc00012fa70 false false []}
2023-04-28T13:12:34+09:00 [INFO][SMF][PFCP] Listen on 10.200.200.1:8805
2023-04-28T13:12:34+09:00 [INFO][SMF][App] Sending PFCP Association Request to UPF[10.200.200.101]
2023-04-28T13:12:34+09:00 [INFO][UDR][Init] UDR Log level is set to [info] level
2023-04-28T13:12:34+09:00 [INFO][UDR][Init] UDR Config Info: Version[1.0.1] Description[UDR initial test configuration]
2023-04-28T13:12:34+09:00 [INFO][UDR][Init] Server started
2023-04-28T13:12:34+09:00 [INFO][UDR][Util] udrconfig Info: Version[1.0.1] Description[UDR initial test configuration]
2023-04-28T13:12:34+09:00 [INFO][NRF][MGMT] Handle NFRegisterRequest
2023-04-28T13:12:34+09:00 [INFO][NRF][MGMT] urilist create
2023-04-28T13:12:34+09:00 [INFO][NRF][MGMT] Create NF Profile
2023-04-28T13:12:34+09:00 [INFO][NRF][MGMT] Location header:  http://127.0.0.10:8000/nnrf-nfm/v1/nf-instances/63e72ce9-6e85-487e-b679-44eb6f334018
2023-04-28T13:12:34+09:00 [INFO][NRF][GIN] | 201 |       127.0.0.1 | PUT     | /nnrf-nfm/v1/nf-instances/63e72ce9-6e85-487e-b679-44eb6f334018 |
2023-04-28T13:12:34+09:00 [INFO][PCF][Init] PCF Log level is set to [info] level
2023-04-28T13:12:34+09:00 [INFO][PCF][Init] Server started
2023-04-28T13:12:34+09:00 [INFO][PCF][Util] pcfconfig Info: Version[1.0.1] Description[PCF initial test configuration]
2023-04-28T13:12:34+09:00 [INFO][NRF][MGMT] Handle NFRegisterRequest
2023-04-28T13:12:34+09:00 [INFO][NRF][MGMT] urilist create
2023-04-28T13:12:34+09:00 [INFO][NRF][MGMT] Create NF Profile
2023-04-28T13:12:34+09:00 [INFO][NRF][MGMT] Location header:  http://127.0.0.10:8000/nnrf-nfm/v1/nf-instances/9394f103-056f-491d-8cb9-2aabbfa61920
2023-04-28T13:12:34+09:00 [INFO][NRF][GIN] | 201 |       127.0.0.1 | PUT     | /nnrf-nfm/v1/nf-instances/9394f103-056f-491d-8cb9-2aabbfa61920 |
2023-04-28T13:12:34+09:00 [INFO][NRF][DSCV] Handle NFDiscoveryRequest
2023-04-28T13:12:34+09:00 [INFO][NRF][GIN] | 200 |       127.0.0.1 | GET     | /nnrf-disc/v1/nf-instances?requester-nf-type=PCF&service-names=nudr-dr&target-nf-type=UDR |
2023-04-28T13:12:35+09:00 [INFO][UDM][Init] UDM Log level is set to [info] level
2023-04-28T13:12:35+09:00 [INFO][UDM][Init] UDM Config Info: Version[1.0.2] Description[UDM initial test configuration]
2023-04-28T13:12:35+09:00 [INFO][UDM][Init] Server started
2023-04-28T13:12:35+09:00 [INFO][UDM][Util] udmconfig Info: Version[1.0.2] Description[UDM initial test configuration]
2023-04-28T13:12:35+09:00 [INFO][NRF][MGMT] Handle NFRegisterRequest
2023-04-28T13:12:35+09:00 [INFO][NRF][MGMT] urilist create
2023-04-28T13:12:35+09:00 [INFO][NRF][MGMT] Create NF Profile
2023-04-28T13:12:35+09:00 [INFO][NRF][MGMT] Location header:  http://127.0.0.10:8000/nnrf-nfm/v1/nf-instances/21dea4c5-a9a5-4c14-b1fd-ae3345264ca0
2023-04-28T13:12:35+09:00 [INFO][NRF][GIN] | 201 |       127.0.0.1 | PUT     | /nnrf-nfm/v1/nf-instances/21dea4c5-a9a5-4c14-b1fd-ae3345264ca0 |
2023-04-28T13:12:35+09:00 [INFO][NSSF][Init] NSSF Log level is set to [info] level
2023-04-28T13:12:35+09:00 [INFO][NSSF][Init] Server started
2023-04-28T13:12:35+09:00 [INFO][NRF][MGMT] Handle NFRegisterRequest
2023-04-28T13:12:35+09:00 [INFO][NRF][MGMT] urilist create
2023-04-28T13:12:35+09:00 [INFO][NRF][MGMT] Create NF Profile
2023-04-28T13:12:35+09:00 [INFO][NRF][MGMT] Location header:  http://127.0.0.10:8000/nnrf-nfm/v1/nf-instances/186267e7-6246-4073-b263-04c174a44103
2023-04-28T13:12:35+09:00 [INFO][NRF][GIN] | 201 |       127.0.0.1 | PUT     | /nnrf-nfm/v1/nf-instances/186267e7-6246-4073-b263-04c174a44103 |
2023-04-28T13:12:35+09:00 [INFO][AUSF][Init] AUSF Log level is set to [info] level
2023-04-28T13:12:35+09:00 [INFO][AUSF][Init] Server started
2023-04-28T13:12:35+09:00 [INFO][AUSF][Init] ausfconfig Info: Version[1.0.2] Description[AUSF initial test configuration]
ausf context =  &{{{0 0} {[] {} <nil>} map[] 0} {{0 0} {[] {} <nil>} map[] 0} 14b4ef15-36e4-410b-894e-800e5cc6de3d ausfGroup001 8000 127.0.0.9 127.0.0.9 http://127.0.0.9:8000 http http://127.0.0.10:8000 map[nausf-auth:{14b4ef15-36e4-410b-894e-800e5cc6de3d nausf-auth 0xc0006cfb00 http REGISTERED   0xc0006cfae8  [] <nil> [] [] <nil> 0 0 0 <nil> <nil> }] [{208 93} {123 45}]  0xc00075f0e0 false}
2023-04-28T13:12:35+09:00 [INFO][NRF][MGMT] Handle NFRegisterRequest
2023-04-28T13:12:35+09:00 [INFO][NRF][MGMT] urilist create
2023-04-28T13:12:35+09:00 [INFO][NRF][MGMT] Create NF Profile
2023-04-28T13:12:35+09:00 [INFO][NRF][MGMT] Location header:  http://127.0.0.10:8000/nnrf-nfm/v1/nf-instances/14b4ef15-36e4-410b-894e-800e5cc6de3d
2023-04-28T13:12:35+09:00 [INFO][NRF][GIN] | 201 |       127.0.0.1 | PUT     | /nnrf-nfm/v1/nf-instances/14b4ef15-36e4-410b-894e-800e5cc6de3d |
=== RUN   TestRegistration
2023-04-28T13:12:35+09:00 [INFO][AMF][NGAP] [AMF] SCTP Accept from: 127.0.0.1:9487
2023-04-28T13:12:35+09:00 [INFO][AMF][NGAP] Create a new NG connection for: 127.0.0.1:9487
2023-04-28T13:12:35+09:00 [ERRO][AMF][NGAP][127.0.0.1:9487] NGAP decode error : OpenType reference value does not match any field
2023-04-28T13:12:43+09:00 [INFO][LIB][PFCP] Remove Request Transaction [1]
2023-04-28T13:12:43+09:00 [ERRO][SMF][App] Failed to setup an association with UPF[10.200.200.101], error:Request Transaction [1]: retry-out
2023-04-28T13:13:03+09:00 [INFO][AMF][Init] Terminating AMF...
2023-04-28T13:13:03+09:00 [INFO][AMF][Consumer] [AMF] Send Deregister NFInstance
2023-04-28T13:13:03+09:00 [INFO][AUSF][Init] Terminating AUSF...
2023-04-28T13:13:03+09:00 [INFO][AUSF][App] Send Deregister NFInstance
2023-04-28T13:13:03+09:00 [INFO][NSSF][Init] Terminating NSSF...
2023-04-28T13:13:03+09:00 [INFO][NSSF][App] Send Deregister NFInstance
2023-04-28T13:13:03+09:00 [INFO][UDR][Init] Terminating UDR...
2023-04-28T13:13:03+09:00 [INFO][UDR][Consumer] Send Deregister NFInstance
2023-04-28T13:13:03+09:00 [INFO][PCF][Init] Terminating PCF...
2023-04-28T13:13:03+09:00 [INFO][PCF][Consumer] Send Deregister NFInstance
2023-04-28T13:13:03+09:00 [INFO][SMF][Init] Terminating SMF...
2023-04-28T13:13:03+09:00 [INFO][SMF][Consumer] Send Deregister NFInstance
2023-04-28T13:13:03+09:00 [INFO][NRF][MGMT] Handle NFDeregisterRequest
2023-04-28T13:13:03+09:00 [INFO][NRF][MGMT] Handle NFDeregisterRequest
2023-04-28T13:13:03+09:00 [INFO][NRF][MGMT] Handle NFDeregisterRequest
2023-04-28T13:13:03+09:00 [INFO][UDM][Init] Terminating UDM...
2023-04-28T13:13:03+09:00 [INFO][UDM][Consumer] Send Deregister NFInstance
2023-04-28T13:13:03+09:00 [INFO][NRF][MGMT] Handle NFDeregisterRequest
2023-04-28T13:13:03+09:00 [INFO][NRF][MGMT] Handle NFDeregisterRequest
2023-04-28T13:13:03+09:00 [INFO][NRF][MGMT] Handle NFDeregisterRequest
2023-04-28T13:13:03+09:00 [INFO][NRF][MGMT] Handle NFDeregisterRequest
2023-04-28T13:13:04+09:00 [INFO][NRF][GIN] | 204 |       127.0.0.1 | DELETE  | /nnrf-nfm/v1/nf-instances/9394f103-056f-491d-8cb9-2aabbfa61920 |
2023-04-28T13:13:04+09:00 [INFO][PCF][Init] Deregister from NRF successfully
2023-04-28T13:13:04+09:00 [INFO][PCF][Init] PCF terminated
2023-04-28T13:13:04+09:00 [FATA][PCF][Init] panic: unexpected call to os.Exit(0) during test
goroutine 206 [running]:
runtime/debug.Stack()
        /usr/local/go/src/runtime/debug/stack.go:24 +0x65
github.com/free5gc/pcf/pkg/service.(*PCF).Start.func1.1()
        /home/nishi/free5gc-deb/free5gc/NFs/pcf/pkg/service/init.go:205 +0x39
panic({0x1162540, 0x162d0c0})
        /usr/local/go/src/runtime/panic.go:884 +0x213
os.Exit(0x0)
        /usr/local/go/src/os/proc.go:67 +0x5a
github.com/free5gc/pcf/pkg/service.(*PCF).Start.func1()
        /home/nishi/free5gc-deb/free5gc/NFs/pcf/pkg/service/init.go:211 +0x5b
created by github.com/free5gc/pcf/pkg/service.(*PCF).Start
        /home/nishi/free5gc-deb/free5gc/NFs/pcf/pkg/service/init.go:201 +0xbb0
exit status 1
FAIL    test    30.568s
upf: no process found
20 packets captured
20 packets received by filter
0 packets dropped by kernel
1047 packets captured
2098 packets received by filter
0 packets dropped by kernel
```

## Environment (please complete the following information):
 - free5GC Version: 662c0191c140da976d403d98190658e3ebc70ee0
 - OS: Ubuntu 20.04
 - Kernel version: 5.15.0-71-generic
 - go version: 1.20.3

**Comment by ShouheiNishi** [comment]
[issue443.pcap.gz](https://github.com/free5gc/free5gc/files/11349780/issue443.pcap.gz)

**Comment by tim-ywliu** [comment]
Thanks for the PR.
